// <auto-generated />
using System;
using BethanysPieShopHRM.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BethanysPieShopHRM.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BethanysPieShopHRM.Shared.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            Name = "China"
                        },
                        new
                        {
                            CountryId = 2,
                            Name = "France"
                        },
                        new
                        {
                            CountryId = 3,
                            Name = "Germany"
                        },
                        new
                        {
                            CountryId = 4,
                            Name = "India"
                        },
                        new
                        {
                            CountryId = 5,
                            Name = "Japan"
                        },
                        new
                        {
                            CountryId = 6,
                            Name = "Jordan"
                        },
                        new
                        {
                            CountryId = 7,
                            Name = "Portugal"
                        },
                        new
                        {
                            CountryId = 8,
                            Name = "Romania"
                        },
                        new
                        {
                            CountryId = 9,
                            Name = "Spain"
                        },
                        new
                        {
                            CountryId = 10,
                            Name = "UK"
                        },
                        new
                        {
                            CountryId = 11,
                            Name = "USA"
                        });
                });

            modelBuilder.Entity("BethanysPieShopHRM.Shared.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("JobCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("CountryId");

                    b.HasIndex("JobCategoryId");

                    b.HasIndex("RegionId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            City = "Paris",
                            Comment = "Lorem Ipsum",
                            CountryId = 2,
                            Email = "paulboc@microsoft.com",
                            FirstName = "Paul",
                            JobCategoryId = 3,
                            JoinedDate = new DateTime(2015, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Cociuba",
                            Latitude = 48.864716000000001,
                            Longitude = 2.3490139999999999,
                            RegionId = 3
                        },
                        new
                        {
                            EmployeeId = 2,
                            City = "Lisbon",
                            Comment = "Lorem Ipsum",
                            CountryId = 7,
                            Email = "crnegule@microsoft.com",
                            FirstName = "Cristian",
                            JobCategoryId = 2,
                            JoinedDate = new DateTime(2015, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Negulescu",
                            Latitude = 38.736946000000003,
                            Longitude = -9.1426850000000002,
                            RegionId = 3
                        });
                });

            modelBuilder.Entity("BethanysPieShopHRM.Shared.JobCategory", b =>
                {
                    b.Property<int>("JobCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("JobCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobCategoryId");

                    b.ToTable("JobCategories");

                    b.HasData(
                        new
                        {
                            JobCategoryId = 1,
                            JobCategoryName = "SE"
                        },
                        new
                        {
                            JobCategoryId = 2,
                            JobCategoryName = "SEE"
                        },
                        new
                        {
                            JobCategoryId = 3,
                            JobCategoryName = "EE"
                        },
                        new
                        {
                            JobCategoryId = 4,
                            JobCategoryName = "EEE"
                        },
                        new
                        {
                            JobCategoryId = 5,
                            JobCategoryName = "TA"
                        },
                        new
                        {
                            JobCategoryId = 6,
                            JobCategoryName = "M1"
                        },
                        new
                        {
                            JobCategoryId = 7,
                            JobCategoryName = "M2"
                        },
                        new
                        {
                            JobCategoryId = 8,
                            JobCategoryName = "M3"
                        },
                        new
                        {
                            JobCategoryId = 9,
                            JobCategoryName = "M4"
                        });
                });

            modelBuilder.Entity("BethanysPieShopHRM.Shared.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegionId");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            RegionId = 1,
                            Name = "Americas"
                        },
                        new
                        {
                            RegionId = 2,
                            Name = "Asia Pacific"
                        },
                        new
                        {
                            RegionId = 3,
                            Name = "EMEA"
                        });
                });

            modelBuilder.Entity("BethanysPieShopHRM.Shared.Employee", b =>
                {
                    b.HasOne("BethanysPieShopHRM.Shared.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BethanysPieShopHRM.Shared.JobCategory", "JobCategory")
                        .WithMany()
                        .HasForeignKey("JobCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BethanysPieShopHRM.Shared.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
